version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true